### ISSUE TITLE
Let all memory be 16-bit

### ISSUE THREAD

**Issue by emard** [Speccery/icy99#2]
CPU is 16-bit only writer but RAM is used as 8-bit with
byte selects.
This is currently required by serial and SPI bootloader
which filles RAM with content of ROMs.

It would be better and simpler that RAM is 16-bit always
and bootloader is modified to buffer 2 bytes to get a 16-bit
and write then

**Comment by Speccery** [comment]
All memory has been 16-bit wide (in SDRAM) for a long while now. The only exception is VDP (video) memory, which is 8-bit wide as the video subsystem (should be) behaving like TMS9918.
