### ISSUE TITLE
Make DSR ROM working

### ISSUE THREAD

**Issue by emard** [Speccery/icy99#3]
Define some bootloader address space for preloading
DSR ROM, it's used in some add-on modules like HEXBUS

DSR ROM should be mapped at 0x4000 from CPU point of view.

I have tried to map something there and I can write it and read
from bootloader SPI, but TI99/4A peek (using editor-assembler)
doesn't show DSR ROM content at address 16384 what I guess should
be 0x4000

**Comment by Speccery** [comment]
Closing these at long last. DSR routines are available at 0x30000. Currently only the TIPI (Raspberry PI) extension is supported. DSR is loaded at SDRAM address 0x30000.
